### ISSUE TITLE
PDF 导出报错   有大佬使用此功能吗   感谢

### ISSUE THREAD

**Issue by chaojidahuazhu** [fanyong920/jvppeteer#97]
Failed to launch the browser process:Cannot run program "/home/eju/.local-browser/linux-722234/chrome-linux/chrome": error=2, 没有那个文件或目录

**Comment by sagexueqi** [comment]
是否执行`BrowserFetcher.downloadIfNotExist(null);` ?

**Comment by ClassmateChen** [comment]
问一下，我用其他浏览器也支持导出PDF么

**Comment by zwjtfd** [comment]
> 是否执行`BrowserFetcher.downloadIfNotExist(null);` ?

在我的项目中已经自动下载过了，但是也会报这个错

**Comment by fanyong920** [comment]
现在自动下载应该用不了了，可以指定chrome路径，手动下载chrome，LanunchOptions有个指定chrome路径的参数




樊勇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fanyong920/jvppeteer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月18日(星期四) 下午4:30
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [fanyong920/jvppeteer] PDF 导出报错   有大佬使用此功能吗   感谢 (Issue #97)





  
是否执行BrowserFetcher.downloadIfNotExist(null); ?
  
在我的项目中已经自动下载过了，但是也会报这个错

**Comment by zwjtfd** [comment]
> 现在自动下载应该用不了了，可以指定chrome路径，手动下载chrome，LanunchOptions有个指定chrome路径的参数 樊勇 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "fanyong920/jvppeteer" ***@***.***&gt;; 发送时间:&nbsp;2024年4月18日(星期四) 下午4:30 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;Re: [fanyong920/jvppeteer] PDF 导出报错 有大佬使用此功能吗 感谢 (Issue #97) 是否执行BrowserFetcher.downloadIfNotExist(null); ? 在我的项目中已经自动下载过了，但是也会报这个错 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

自动下载和指定执行路径的方式在我本地windows上都能正常执行，但是部署到linux上就会报Failed to launch the browser process:Cannot run program "XXX": error=2, No such file or directory的错误，请问大佬如何解决

**Comment by zwjtfd** [comment]
补充说明下，部署是基于openjdk:8u201-jdk-alpine3.9镜像进行的docker部署

**Comment by fanyong920** [comment]
docker里面应该也可以下载chrome的吧，让运维下载chrome，给路径你，哈哈，具体我不太懂，很久没代码了




樊勇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fanyong920/jvppeteer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月18日(星期四) 下午5:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fanyong920/jvppeteer] PDF 导出报错   有大佬使用此功能吗   感谢 (Issue #97)





 
补充说明下，部署是基于openjdk:8u201-jdk-alpine3.9镜像进行的docker部署

**Comment by fanyong920** [comment]
No such file or directory应该路径不对




樊勇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fanyong920/jvppeteer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月18日(星期四) 下午4:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fanyong920/jvppeteer] PDF 导出报错   有大佬使用此功能吗   感谢 (Issue #97)





  
现在自动下载应该用不了了，可以指定chrome路径，手动下载chrome，LanunchOptions有个指定chrome路径的参数 樊勇 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "fanyong920/jvppeteer" @.&gt;; 发送时间:&nbsp;2024年4月18日(星期四) 下午4:30 @.&gt;; @.&gt;; 主题:&nbsp;Re: [fanyong920/jvppeteer] PDF 导出报错 有大佬使用此功能吗 感谢 (Issue #97) 是否执行BrowserFetcher.downloadIfNotExist(null); ? 在我的项目中已经自动下载过了，但是也会报这个错 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
自动下载和指定执行路径的方式在我本地windows上都能正常执行，但是部署到linux上就会报Failed to launch the browser process:Cannot run program "XXX": error=2, No such file or directory的错误，请问大佬如何解决

**Comment by zwjtfd** [comment]
> No such file or directory应该路径不对 樊勇 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "fanyong920/jvppeteer" ***@***.***&gt;; 发送时间:&nbsp;2024年4月18日(星期四) 下午4:48 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [fanyong920/jvppeteer] PDF 导出报错 有大佬使用此功能吗 感谢 (Issue #97) 现在自动下载应该用不了了，可以指定chrome路径，手动下载chrome，LanunchOptions有个指定chrome路径的参数 樊勇 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "fanyong920/jvppeteer" @.&gt;; 发送时间:&nbsp;2024年4月18日(星期四) 下午4:30 @.&gt;; @.&gt;; 主题:&nbsp;Re: [fanyong920/jvppeteer] PDF 导出报错 有大佬使用此功能吗 感谢 (Issue #97) 是否执行BrowserFetcher.downloadIfNotExist(null); ? 在我的项目中已经自动下载过了，但是也会报这个错 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt; 自动下载和指定执行路径的方式在我本地windows上都能正常执行，但是部署到linux上就会报Failed to launch the browser process:Cannot run program "XXX": error=2, No such file or directory的错误，请问大佬如何解决 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

对应目录确实是已经存在文件了，但是不知道为什么还会报这个错

**Comment by fanyong920** [comment]
去群里问问，很多人部署过在docker


201719448&nbsp; qq






樊勇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fanyong920/jvppeteer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月18日(星期四) 晚上9:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fanyong920/jvppeteer] PDF 导出报错   有大佬使用此功能吗   感谢 (Issue #97)





  
No such file or directory应该路径不对 樊勇 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "fanyong920/jvppeteer" @.&gt;; 发送时间:&nbsp;2024年4月18日(星期四) 下午4:48 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [fanyong920/jvppeteer] PDF 导出报错 有大佬使用此功能吗 感谢 (Issue #97) 现在自动下载应该用不了了，可以指定chrome路径，手动下载chrome，LanunchOptions有个指定chrome路径的参数 樊勇 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "fanyong920/jvppeteer" @.&gt;; 发送时间:&nbsp;2024年4月18日(星期四) 下午4:30 @.&gt;; @.&gt;; 主题:&nbsp;Re: [fanyong920/jvppeteer] PDF 导出报错 有大佬使用此功能吗 感谢 (Issue #97) 是否执行BrowserFetcher.downloadIfNotExist(null); ? 在我的项目中已经自动下载过了，但是也会报这个错 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt; 自动下载和指定执行路径的方式在我本地windows上都能正常执行，但是部署到linux上就会报Failed to launch the browser process:Cannot run program "XXX": error=2, No such file or directory的错误，请问大佬如何解决 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
对应目录确实是已经存在文件了，但是不知道为什么还会报这个错
